---
title: "Statistical Case Studies - Project 1 part 2"
author: "Georgia Ettles, Mayez Haris and Niharika Peddinenikalva"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(1234)
library(ggplot2)
library(tidyverse)
library(gridExtra)
library(countrycode)
library(visdat)
library(interactions)
library(forestplot)
library(RColorBrewer)
library(viridis)
library(xtable)
```

# Pre-processing

```{r easyshare}
# Loading data
load("easySHARE_rel8_0_0.rda")
data <- easySHARE_rel8_0_0

# Renaming some variables to make them less cryptic
data <- data %>% rename(
  native = dn004_mod,
  loc = iv009_mod,
  edu = isced1997_r,
  outside_help = sp002_mod,
  life_quality = casp,
  doc_vis = hc002_mod,
  nursing = hc029_,
  vig_act = br015_,
  job_situ = ep005_,
  country_name = country_mod
)

# Computing and adding composite cognitive score
cogvars <- c("recall_1", "recall_2", "orienti", "numeracy_1", "numeracy_2")
cog = data[cogvars]

numeracy = rep(NA,dim(cog)[1])
numeracy[cog$numeracy_1 >= 0 & cog$numeracy_2 >= 0] = (cog$numeracy_1[cog$numeracy_1 >= 0 & cog$numeracy_2 >= 0] + cog$numeracy_2[cog$numeracy_1 >= 0 & cog$numeracy_2 >= 0] )/2
numeracy[cog$numeracy_1 >= 0 & cog$numeracy_2 < 0] = cog$numeracy_1[cog$numeracy_1 >= 0 & cog$numeracy_2 < 0]
numeracy[cog$numeracy_1 < 0 & cog$numeracy_2 >= 0] = cog$numeracy_2[cog$numeracy_1 < 0 & cog$numeracy_2 >= 0]
cog$numeracy = numeracy

cogscore = rep(NA,dim(cog)[1])
ind = cog$recall_1 >= 0 & cog$recall_2 >= 0 & cog$orienti >= 0 & !is.na(numeracy)
cogscore[ind] = cog$recall_1[ind] + cog$recall_2[ind] +  cog$orienti[ind] + cog$numeracy[ind]
cog$cogscore = cogscore
data$cogscore<-cog$cogscore

# Replace country codes with country names
data$country_name <- countrycode(factor(data$country_name),
  origin = "iso3n",
  destination = "country.name"
)


# Set missing values to NA       
data[data < 0] <- NA

```



```{r}
# Tables to figure out which country and wave would be suitable to model with 
length(unique(data$mergeid))
table(data$wave,data$int_year)
table(data$country_name, data$wave)
```

```{r vars}
# Lists of variables that would be used in the model
variable_list <- c("age", "female", "native", "loc", "edu", 
                   "outside_help", "chronic_mod", "life_quality", "eurod", 
                   "doc_vis", "nursing", "iadlza",
                   "maxgrip", "vig_act", "job_situ")

binary_list <- c("female", "native", "outside_help",  
                 "hosp_stay", "nursing")

categorical_list <- c("loc", "edu", "hhsize", "chronic_mod", 
                     "life_quality", "eurod", "doc_vis", "iadlza", "adla" , 
                     "maxgrip", "vig_act", "job_situ", "ends_meet")

continuous_list <- c("age")

```


```{r factoring}
# Factoring binary variables as dummy variables
for (column in binary_list) {
  if (column != "nursing") {
    data[, column] <- ifelse(data[, column] == "1", 1, 0)
  } else {
    data$nursing <- ifelse(data[, column] == "5", 0, 1)
  }
  data[, column] <- factor(data[, column], levels = c(0, 1), labels = c("No", "Yes"))
}


# Factor non-binary variables
for (column in categorical_list) {
  data[, column] <- factor(data[, column])
}

# Simplifying levels for specific categorical variables
levels(data$edu) <- list(
  "Secondary and Below" = as.character(0:3),
  "Post Secondary" = as.character(4:6),
  "Other" = as.character(95:96)
)


levels(data$eurod) <- list(
  "Not Depressed" = as.character(0:3),
  "Somewhat Depressed" = as.character(4:6),
  "Relatively Depressed" = as.character(7:9),
  "Very Depressed" = as.character(10:12)
)


levels(data$loc) <- list(
  "City_sub" = as.character(1:2),
  "Town_rural" = as.character(3:5)
)


levels(data$chronic_mod) <- list(
  "0" = as.character(0),
  "1-3" = as.character(1:3),
  "4-6" = as.character(4:6),
  "7-10" = as.character(7:10)
)


levels(data$adla) <- list(
  "High Mobility" = as.character(0:2),
  "Low Mobility" = as.character(3:5)
)


levels(data$iadlza) <- list(
  "Low Difficulty" = as.character(0:2),
  "High Difficulty" = as.character(3:5)
)


levels(data$vig_act) <- list(
  "Often" = as.character(1:2),
  "Rarely" = as.character(3:4)
)


levels(data$maxgrip) <- list(
  "Low" = as.character(1:29),
  "High" = as.character(30:99)
)


levels(data$life_quality) <- list(
  "Low" = as.character(12:24),
  "Moderate" = as.character(25:36),
  "High" = as.character(37:48)
)


levels(data$doc_vis) <- list(
  "0-10" = as.character(0:10),
  "More than 10" = as.character(11:98)
)


levels(data$job_situ) <- list(
  "Retired" = as.character(1),
  "Employed" = as.character(2),
  "Unemployed" = as.character(3),
  "Sick_Disabled" = as.character(4),
  "Homemaker" = as.character(5),
  "Other" = as.character(97)
)

```



```{r}
# Pick a country and wave and subset the data to choose relevant variables and cogscore for the model
working_data <- na.omit(data %>% 
  filter(wave == 4, country_name == "Estonia") %>% 
  select(all_of(variable_list), "cogscore"))


# Visualise the data to see check proportion of missing data (Note: this code was used with working_data that did not have the na.omit() function to analyse the proportion of missing data)
summary(working_data$cogscore)
vis_miss(working_data)


# Removing 200 observations to get training data set
remove_indices <- sample.int(nrow(working_data), 200)
training_data <- working_data[-remove_indices, ]
removed_data <- working_data[remove_indices, ]

# Display summary statistics
summary(training_data)
```


# Visualising some of the chosen explanatory variables 
```{r}
# Box plots to show how cogscore varies across different variables
# Box plot for how cogscore varies across levels of education completed
edu_plot <- working_data %>% filter(edu != "Other") %>%
  ggplot(aes(x = edu, y = cogscore, fill = edu)) +
  geom_boxplot(show.legend = F) + 
  xlab("Education level completed") + ylab("Composite Cognitive score") + coord_flip() + stat_boxplot(geom = "errorbar", width = 0.2) + theme(axis.text.y = element_text(size = rel(1.5), angle = 45, hjust = 0.5), axis.text.x = element_text(size = rel(1.5), hjust = 0.5), axis.title = element_text(size = rel(1.5)))
edu_plot
ggsave("edu_plot.png", edu_plot)

# Box plot for how cogscore varies across number of chronic diseases
chronic_plot <- working_data %>%
  ggplot(aes(x = chronic_mod, y = cogscore, fill = chronic_mod)) + geom_boxplot(show.legend = F) + xlab("Number of chronic diseases") + ylab("Composite Cognitive score") + coord_flip() + stat_boxplot(geom = "errorbar", width = 0.2) + theme(axis.text.y = element_text(size = rel(1.5), hjust = 0.5), axis.text.x = element_text(size = rel(1.5), hjust = 0.5), axis.title = element_text(size = rel(1.5)))
chronic_plot
ggsave("chronic_plot.png", chronic_plot)


# Box plot for how cogscore varies across EURO-D depression scales
eurod_plot <- working_data %>%
  ggplot(aes(x = eurod, y = cogscore, fill = eurod)) + geom_boxplot(show.legend = F) + xlab("Depression scale EURO-D") + ylab("Composite Cognitive score") + coord_flip() + stat_boxplot(geom = "errorbar", width = 0.2) + theme(axis.text.y = element_text(size = rel(1.5), angle = 45, hjust = 0.5), axis.text.x = element_text(size = rel(1.5), hjust = 0.5), axis.title = element_text(size = rel(1.5)))
eurod_plot
ggsave("eurod_plot.png", eurod_plot)


# Box plot for how cogscore varies across frequence of vigorous activities
vig_act_plot <- working_data %>%
  ggplot(aes(x = vig_act, y = cogscore, fill = vig_act)) + geom_boxplot(show.legend = F) + xlab("Frequency of Vigorous Activities") + ylab("Composite Cognitive score") + coord_flip() + stat_boxplot(geom = "errorbar", width = 0.2) + theme(axis.text.y = element_text(size = rel(1.5), angle = 45, hjust = 0.5), axis.text.x = element_text(size = rel(1.5), hjust = 0.5), axis.title = element_text(size = rel(1.5)))
vig_act_plot
ggsave("vig_act_plot.png", vig_act_plot)


# Box plot for how cogscore varies across difficulty in instrumental activities of daily living
iadlza_plot <- working_data %>%
  ggplot(aes(x = iadlza, y = cogscore, fill = iadlza)) +
  geom_boxplot(show.legend = F) + xlab("Difficulties with Instrumental Activities") + ylab("Composite Cognitive score") + coord_flip() + stat_boxplot(geom = "errorbar", width = 0.2) + theme(axis.text.y = element_text(size = rel(1.5), angle = 45, hjust = 0.5), axis.text.x = element_text(size = rel(1.5), hjust = 0.5), axis.title = element_text(size = rel(1.5)))
iadlza_plot
ggsave("iadlza_plot.png", iadlza_plot)


# Box plot for how cogscore varies differently across age groups for males and females
fitinteract <- lm(cogscore ~ female* age, data = working_data)
age_female_plot <- interact_plot(fitinteract, pred = age, modx = female, interval = TRUE, line.thickness = 0.3, point.alpha = 1, x.label = "Age", y.label = "Composite Cognitive Score", legend.main = "Female") + theme(axis.text.y = element_text(size = rel(1.5), hjust = 0.5), axis.text.x = element_text(size = rel(1.5), hjust = 0.5), axis.title = element_text(size = rel(1.5)))
age_female_plot
ggsave("age_female_plot.png", age_female_plot)
```


# The Model

```{r}
# Define model formula for response variable cogscore
mod <- cogscore ~ age + female + native + loc + edu + outside_help + 
  chronic_mod + life_quality + eurod + doc_vis + nursing + iadlza  + maxgrip + vig_act + job_situ + loc:outside_help + age:doc_vis + 
  nursing:iadlza

# Define model
fit <- lm(mod, data = training_data)

# Display model assumptions through residuals 
par(mfrow = c(2, 2))
plot(fit)

# Save the summary of the model along with confidence intervals for the coefficient estimates 
fit_summary <- summary(fit)
fit_intervals <- confint(fit)
fit_summary

# Check the model by comparing AIC
better_fit <- step(fit, trace = F)
```


```{r}
# Set up a table that can be exported through LaTeX for the report
fit_summary_sign <- fit_summary$coefficients[ , 4]  # Pull out p-values
fit_summary_stars <- NA                             # Named vector with significance stars

# Define how the symbols appear for different significance levels
fit_summary_stars[fit_summary_sign < 0.1] <- "."  
fit_summary_stars[fit_summary_sign < 0.05] <- "*"
fit_summary_stars[fit_summary_sign < 0.01] <- "**"
fit_summary_stars[fit_summary_sign < 0.001] <- "***"
fit_summary_stars[is.na(fit_summary_stars)] <- ""
names(fit_summary_stars) <- names(fit_summary_sign)

# Make a data frame of the summary for the model coefficients to be exported as a LaTeX table
fit_df <- cbind(data.frame("Estimate" = fit_summary$coefficients[, 1]), data.frame("CI_lower" = fit_intervals[, 1], "CI_upper" = fit_intervals[, 2]), data.frame("p-value" = fit_summary$coefficients[, 4]), data.frame(Significance = fit_summary_stars))
fit_rownames <- c("Intercept", "age", "female", "native", "loc_Town_rural", 
                  "edu_Post_Secondary", "outside_help", 
                  "chronic_mod1-3", "chronic_mod4-6", "chronic_mod7-10",
                  "life_quality_Moderate", "life_quality_High", 
                  "eurod_Somewhat_Depressed", "eurod_Relatively_Depressed",
                  "eurod_Very_Depressed", "doc_vis_More_than_10",  
                  "nursing", "iadlza_High_Difficulty", 
                  "maxgrip_High", "vig_act_Rarely", "job_situ_Employed", 
                  "job_situ_Unemployed", "job_situ_Sick_Disabled", 
                  "job_situ_Homemaker", "job_situ_Other", 
                  "loc_Town_rural:outside_help", 
                  "age:doc_vis_More_than_10", "nursing:iadlza_High_Difficulty")
rownames(fit_df) <- fit_rownames
xtable(fit_df)
```

```{r}
# Make a forest plot to display key explanatory variables, their coefficient estimates and confidence intervals graphically.

# Choose the key explanatory variables
forest_names <- c("age", "female", "native", "loc_Town_rural", "edu_Post_Secondary",
                  "outside_help", "iadlza_High_Difficulty", "vig_act_Rarely", 
                  "age:doc_vis_More_than_10")           

# Construct a data frome for the forest plot with the relevant data
forest_df <- data.frame(Variable = forest_names, 
                             Estimate = round(fit_df[forest_names, 1], 2), 
                             CI_lower = round(fit_df[forest_names, 2], 2), 
                             CI_upper = round(fit_df[forest_names, 3], 2),
                             p.value = round(fit_df[forest_names, 4], 2),
                             Significance = fit_df[forest_names, 5]) 

# Plot and save the forest plot
jpeg(filename = "Forestplot.jpeg", units = "in", width = 10, height = 7, res = 300)
forest_df |> 
  forestplot(labeltext = c(Variable, Estimate, Significance),
  mean = Estimate, 
  lower = CI_lower,
  upper = CI_upper,
  boxsize = 0.15, xlab = "Coefficient estimate value",
  fn.ci_norm= "fpDrawCircleCI", 
  colgap = unit(3, "mm"),
  vertices = T,
  cex = 1.4
  ) |>
  fp_set_style(lines = "red", box = "black", 
               align = "rrc",
               txt_gp = fpTxtGp(xlab = gpar(cex = 1), 
                                ticks = gpar(cex = 1))) |>
  fp_add_header(Estimate = "Estimate", Variable = "Variables",  Significance = "Significance") |>
  fp_add_lines() |>
  fp_set_zebra_style("#EFEFEF")
dev.off()

```


# Model assessment 
```{r set-up-scores}
# Define a function that computes the scores of a given model with given test data
scores_se <- function(model, test_data) {
  
  # Find the predicted values for cogscore of each observation
  predicted_vals <- predict(model, newdata = test_data) 
  
  # Compute the square root of the mean of the squared prediction errors
  se_scores <- (predicted_vals - test_data$cogscore)**2
  rmse_score <- sqrt(mean(se_scores))
  
  rmse_score      # Return the root mean squared error
  
}

# Choose 4 different test datasets

# Test data same as training data (Estonia, wave 4)
test1_data <- training_data

# Test data is removed data (Estonia, wave 4)
test2_data <- removed_data

# Test data is same wave (4) different country (Austria)
test3_data <- na.omit(data %>% 
  filter(wave == 4, country_name == "Austria") %>% 
  select(all_of(variable_list), "cogscore"))

# Test data is same country (Estonia) different wave (6)
test4_data <- na.omit(data %>% 
  filter(wave == 6, country_name == "Estonia") %>% 
  select(all_of(variable_list), "cogscore"))
```

```{r calc-scores}
# Compute the scores for the main model using the different sets of test data
test1_scores <- scores_se(model = fit, test_data = test1_data)
test2_scores <- scores_se(model = fit, test_data = test2_data)
test3_scores <- scores_se(model = fit, test_data = test3_data)
test4_scores <- scores_se(model = fit, test_data = test4_data)

```

```{r}
# Define minimal model of cogscore depending on age to compare scores with the main model
min_mod <- cogscore ~ age

# Define model 
min_fit <- lm(min_mod, data = training_data)

# Display model assumptions through residuals
par(mfrow = c(2, 2))
plot(min_fit)

# Compute scores for the minimal model using the different sets of test data
test1_scores_min_mod <- scores_se(model = min_fit, test_data = test1_data)
test2_scores_min_mod <- scores_se(model = min_fit, test_data = test2_data)
test3_scores_min_mod <- scores_se(model = min_fit, test_data = test3_data)
test4_scores_min_mod <- scores_se(model = min_fit, test_data = test4_data)
```



```{r}
# Create a data frame of the scores for each of the test data for both models to be exported in LaTeX

scores <- data.frame(
  "Scores of Main model" = c(test1_scores, test2_scores, test3_scores, test4_scores),
  "Scores of Minimal model" = c(test1_scores_min_mod, test2_scores_min_mod, test3_scores_min_mod, test4_scores_min_mod))

rownames(scores) <- c("Test 1", "Test 2", "Test 3", "Test 4")

xtable(scores)
```




# Todo
prediction errors 